name: Code Format Check

on:
  pull_request:
    branches:
      - master

jobs:
  prettier:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier . --check
